version: '3.9'

services:
  user-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgresql/data

  driver-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: driver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: driverdb
    volumes:
      - driver-db-data:/var/lib/postgresql/data

  ride-db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ride
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ridedb
    volumes:
      - ride-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  location-db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: location
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locationdb
    volumes:
      - location-db-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  user-db-data:
  driver-db-data:
  ride-db-data:
  payment-db-data:
  location-db-data:
